### ISSUE TITLE
Not sure how the interval part works

### ISSUE THREAD

**Issue by yvan-vivid** [lectromoe/Pomodoro#1]
Hey, thanks for sharing this two years ago. Not sure if you are still working on stuff like this, but as I learn Dioxus I was trying to understand how to emulate setting a callback/future running on a regular interval to do updates. I figured out how to do it in my case, but looking at your source, I can't seem to figure out where the updating is happening each second to tick the clock. Would love to know if you could point this out. Either way, thanks for sharing the example.

**Comment by kualta** [comment]
hey @yvan-vivid! thanks for reaching out.
the implementation of this timer does not rely on updating clock every second, but rather on marking a deadline point in time in the future, and checking how long we have left until then.

here's the part that returns a duration to check the time left:
```rust
    fn time_left(&self) -> Duration {
        self.deadline
            .checked_duration_since(Instant::now())
            .unwrap_or(Duration::ZERO)
    }
```

and we call it in the default case of this match in the `Display` implementation:
```rust
impl Display for PomoTimer {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let time_left = match self.state {
            TimerState::Paused(paused_at) => self
                .deadline
                .checked_duration_since(paused_at)
                .unwrap_or(Duration::ZERO),
            TimerState::Inactive => self.work_duration,
            _ => self.time_left(),  // <---- right here
        };
        let minutes_left = time_left.as_secs() / 60;
        let secs_left = time_left.as_secs() % 60;

        write!(f, "{}:{:0>2}", minutes_left, secs_left)
    }
}
```
which is then updated repeatedly, updating the actual text that the clock displays. 
if you have any questions feel free reach out again! bear in mind that this pomo timer uses an outdated dioxus version and if you have dioxus-specific questions you can also take a look at their [discord server](https://discord.gg/jBrjy5eDp6)

big love!

**Comment by yvan-vivid** [comment]
Thanks gang. I appreciate your thoughts. Indeed, I see how the style has changed with the more recent Dioxus. The part I still don't get is why the display gets repeatedly updated. I was experimenting with something similar and landed on
```rust
fn App() -> Element {
    let mut time_signal = use_signal(vivid_time_now);
    use_future(move || async move {
        loop {
            sleep(Duration::from_millis(1000)).await;
            time_signal.set(vivid_time_now());
        }
    });

    let time: VividTimeWithFraction = time_signal();
    rsx! { div { background_color: "black", VividTimeDisplay { time } } }
}
```
wherein I create a simple future that updates a signal doing a rerender. I'm pretty satisfied with this solution for the moment, but was just curious. Will check out the discord server for sure.

**Comment by kualta** [comment]
if you're only interested in time now i think that's a good enough implementation, but if you were to count time down and relied on sleep(1000) for that to be accurate, over time you'd accumulate extra milliseconds that would make the clock inaccurate.

also, i don't think pomo's implementation requires constant rerenders, i think rerendering it every 500ms would be sufficient. i just haven't implemented it lol
